[package]
name = "mvp01"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "OSS Code Analyzer and LLM-Ready Summarizer"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/mvp01"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
sled = "0.34"
zip = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
indicatif = "0.17"
chrono = "0.4"

[dev-dependencies]
tempfile = "3.5"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3

[profile.dev]
opt-level = 1

[profile.test]
opt-level = 3
