[package]
name = "oss_code_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
sled = "0.34"
zip = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
indicatif = "0.17"
chrono = "0.4"
tree-sitter = "0.20"
tree-sitter-rust = "0.20"
tree-sitter-javascript = "0.20"
tree-sitter-python = "0.20"
tree-sitter-java = "0.20"
tree-sitter-c = "0.20"
tree-sitter-cpp = "0.20"
tree-sitter-go = "0.20"
prost = "0.11"
flate2 = "1.0"
tonic = "0.9"
rayon = "1.7"
colored = "2.0"

[build-dependencies]
tonic-build = "0.9"

[dev-dependencies]
tempfile = "3.5"
