# ===== Level 4 (Top): Project Metadata =====
[package]
name = "phase01"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "ZIP file analysis and storage tool"
license = "MIT"

# ===== Level 3: Feature Configuration =====
[features]
default = ["metrics", "tracing"]
metrics = ["dep:metrics", "dep:metrics-util"]
tracing = ["dep:tracing", "dep:tracing-subscriber"]

# ===== Level 2: Dependencies by Category =====
[dependencies]
# Async Runtime
tokio = { version = "1.36.0", features = ["full"] }
futures = "0.3.30"
async-trait = "0.1.77"

# Data Processing
bytes = "1.5.0"
zip = "0.6.6"
encoding_rs = "0.8.33"
chardetng = "0.1.17"
crc32fast = "1.3.2"

# Storage
sled = "0.34.7"
bincode = "1.3.3"

# CLI & Arguments
clap = { version = "4.5.1", features = ["derive"] }
indicatif = "0.17.8"
colored = "2.1.0"

# Error Handling
thiserror = "1.0.57"
anyhow = "1.0.79"

# Serialization
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

# Metrics & Monitoring
metrics = "0.22.1"
metrics-util = "0.16.2"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# Utilities
tempfile = "3.10.0"
lru = "0.12.2"

# ===== Level 1: Development Dependencies =====
[dev-dependencies]
tokio-test = "0.4.3"
pretty_assertions = "1.4.0"
test-log = "0.2.14"
rand = "0.8.5"

# ===== Benchmark Configuration =====
[[bench]]
name = "zip_processing"
harness = false
