# ===== Level 4 (Top): Project Metadata =====
[package]
name = "phase01"
version = "0.1.0"
edition = "2021"
authors = ["amuldotexe <https://twitter.com/amuldotexe>"]
description = "ZIP file analysis and storage tool"
license = "MIT"

# ===== Level 3: Feature Configuration =====
[features]
default = ["metrics", "tracing"]
metrics = ["dep:metrics", "dep:metrics-util"]
tracing = ["dep:tracing", "dep:tracing-subscriber"]

# ===== Level 2: Dependencies by Category =====
[dependencies]
# Async Runtime - Latest stable versions
tokio = { version = "1.36.0", features = ["full"] }
futures = "0.3.30"
async-trait = "0.1.77"
tokio-util = { version = "0.7.10", features = ["codec"] }
tokio-stream = "0.1.14"

# Data Processing - Verified compatible versions
bytes = "1.5.0"
zip = { version = "0.6.6", features = ["deflate", "time"] }
encoding_rs = "0.8.33"
chardetng = "0.1.17"
crc32fast = "1.3.2"

# Storage - Using RocksDB instead of sled for better maintenance
rocksdb = { version = "0.21.0", features = ["multi-threaded-cf"] }
bincode = "1.3.3"

# CLI & Arguments - Latest stable versions
clap = { version = "4.5.1", features = ["derive"] }
indicatif = "0.17.8"
colored = "2.1.0"

# Error Handling - Latest versions
thiserror = "1.0.57"
anyhow = "1.0.79"

# Serialization - Latest stable
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

# Metrics & Monitoring (Optional) - Latest stable
metrics = { version = "0.21.1", optional = true }
metrics-util = { version = "0.16.2", optional = true }
tracing = { version = "0.1.40", optional = true }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"], optional = true }

# Time & Date - Latest stable with serde support
chrono = { version = "0.4.35", features = ["serde"] }

# System Information - Latest stable
sys-info = "0.9.1"

# Utilities - Latest stable
tempfile = "3.10.0"
lru = "0.12.2"

# ===== Level 1: Development Dependencies =====
[dev-dependencies]
tokio-test = "0.4.3"
pretty_assertions = "1.4.0"
test-log = "0.2.14"
rand = "0.8.5"
